# Generated by Django 4.2 on 2023-05-23 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_address', models.CharField(max_length=255)),
                ('ngo_description', models.CharField(max_length=255)),
                ('ngo_phone', models.CharField(max_length=11)),
                ('ngo_bank_name', models.CharField(max_length=255)),
                ('ngo_account_title', models.CharField(max_length=255)),
                ('ngo_account_no', models.CharField(max_length=255)),
                ('ngo_image', models.ImageField(upload_to='')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_updated', models.DateTimeField(null=True)),
                ('voided', models.BooleanField(default=False)),
                ('date_voided', models.DateTimeField(null=True)),
                ('void_reason', models.CharField(max_length=1024, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='ngo_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo_updater', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ngo_voider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=50)),
                ('campaign_description', models.CharField(max_length=255)),
                ('campaign_image', models.ImageField(upload_to='')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_updated', models.DateTimeField(null=True)),
                ('voided', models.BooleanField(default=False)),
                ('date_voided', models.DateTimeField(null=True)),
                ('void_reason', models.CharField(max_length=1024, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('NGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharityGo.ngo')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_updater', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_voider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
