# Generated by Django 4.2 on 2023-05-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityGo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_image',
            field=models.ImageField(upload_to='./CharityGo/campaign_images'),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='ngo_image',
            field=models.ImageField(upload_to='./CharityGo/ngo_images'),
        ),
    ]
