# Generated by Django 4.2 on 2023-05-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityGo', '0002_alter_campaign_campaign_image_alter_ngo_ngo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='ngo_name',
            field=models.CharField(default='jdc', max_length=50),
            preserve_default=False,
        ),
    ]
