# Generated by Django 4.2 on 2023-05-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityGo', '0003_ngo_ngo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='ngo_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
