# Generated by Django 4.2 on 2023-05-30 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CharityGo', '0005_alter_campaign_campaign_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorRequest',
            fields=[
                ('request_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('request_name', models.CharField(max_length=50)),
                ('request_description', models.CharField(max_length=255)),
                ('request_image', models.ImageField(upload_to='images/')),
                ('request_price', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_updated', models.DateTimeField(null=True)),
                ('voided', models.BooleanField(default=False)),
                ('date_voided', models.DateTimeField(null=True)),
                ('void_reason', models.CharField(max_length=1024, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('NGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharityGo.ngo')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='request_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_updater', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_voider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=50)),
                ('donor_cnic', models.IntegerField(max_length=13)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_updated', models.DateTimeField(null=True)),
                ('voided', models.BooleanField(default=False)),
                ('date_voided', models.DateTimeField(null=True)),
                ('void_reason', models.CharField(max_length=1024, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='donor_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_updater', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_voider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donation_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('date_updated', models.DateTimeField(null=True)),
                ('voided', models.BooleanField(default=False)),
                ('date_voided', models.DateTimeField(null=True)),
                ('void_reason', models.CharField(max_length=1024, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('Donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharityGo.donor')),
                ('SponsorRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CharityGo.sponsorrequest')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='donation_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_updater', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donation_voider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
